# Generated by Django 5.1.4 on 2024-12-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria_produtos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('quanto_custa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Minha_empresa.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/<django.db.models.fields.related.ForeignKey>/produto')),
                ('alt', models.CharField(max_length=200)),
                ('produto_refere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Minha_empresa.produto')),
            ],
        ),
    ]
